#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}/bin/activate

echo "run sentry upgrade"
sentry --config=$OPENSHIFT_REPO_DIR/sentry.conf.py upgrade