#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -f ${OPENSHIFT_DATA_DIR}${OPENSHIFT_APP_NAME}/bin/activate ];
then
    virtualenv --no-site-packages --clear $OPENSHIFT_DATA_DIR/$OPENSHIFT_APP_NAME
fi

source ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}/bin/activate
export PIP_DOWNLOAD_CACHE=${OPENSHIFT_TMP_DIR}.pip/cache

pip install --log=${OPENSHIFT_TMP_DIR}.pip/pip.log -r ${OPENSHIFT_REPO_DIR}requirements.txt

sentry --config=$OPENSHIFT_REPO_DIR/sentry.conf.py upgrade
