#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -f ${OPENSHIFT_DATA_DIR}${OPENSHIFT_APP_NAME}/bin/activate ];
then
    virtualenv $OPENSHIFT_DATA_DIR/$OPENSHIFT_APP_NAME
fi

source ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}/bin/activate
export PIP_DOWNLOAD_CACHE=${OPENSHIFT_TMP_DIR}.pip/cache

if [ -f ${OPENSHIFT_REPO_DIR}/requirements.txt ];
then
    pip install -r ${OPENSHIFT_REPO_DIR}/requirements.txt
fi

