#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

echo "start app"
source ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}/bin/activate

#set sentry.conf path
export SENTRY_CONF="$OPENSHIFT_REPO_DIR/sentry.conf.py"

uwsgi -s $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT --socket-protocol http --module sentry.wsgi:application --pp $OPENSHIFT_REPO_DIR/lib/python2.7/site-packages/sentry -d $OPENSHIFT_DIY_LOG_DIR/app.log --pidfile $OPENSHIFT_TMP_DIR/uwsgi.pid
