#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

source ${OPENSHIFT_DATA_DIR}${OPENSHIFT_APP_NAME}/bin/activate

sentry --config=$OPENSHIFT_REPO_DIR/sentry.conf.py start